exports.SESSION_OUTPUT = 'SESSION_OUTPUT';
exports.SESSION_ERROR = 'SESSION_ERROR';
exports.SESSION_CONNECTED = 'SESSION_CONNECTED';
exports.SESSION_DISCONNECTED = 'SESSION_DISCONNECTED';
exports.SESSION_CLOSED = 'SESSION_CLOSED';
