exports.TELNET_HIDE_ECHO = 1;
exports.TELNET_TERMINAL_TYPE = 24;
exports.TELNET_NEGOTIATE_WINDOW_SIZE = 31;

// Web-socket outgoing actions
exports.SESSION_HIDE_PROMPT_REQUESTED = 'SESSION_HIDE_PROMPT_REQUESTED';
exports.SESSION_SHOW_PROMPT_REQUESTED = 'SESSION_SHOW_PROMPT_REQUESTED';
